<?= $this->doctype() ?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

  <?= $this->headMeta()
  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?= $this->headLink(['rel' => '', 'type' => 'image/', 'href' => $this->basePath() . '/img/'])
  ->prependStylesheet($this->basePath('css/style.css'))
  ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
  ?>

  <!-- Scripts -->
  <?= $this->inlineScript()
  ->prependFile($this->basePath('jquery-3.2.1.slim.min.js'))
  ->prependFile($this->basePath('umd/popper.min.js'))
  ->prependFile($this->basePath('js/bootstrap.min.js'))
  ?>
</head>
<body>
 <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>
<div class="container">
  <?= $this->content ?>
  <hr>
  <footer>
    <p></p>
  </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
