<div class="jumbotron">
    <h1></h1>

    <p>
    
        <a href="" target="_blank"></a>.
        
    </p>

    <p><a class="btn btn-success btn-lg" href="" target="_blank"></a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p>
                <a href=""></a>
                 <a href=""></a>
                </p>

                <p><a class="btn btn-success pull-right" href="" target="_blank"></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p> 
                    <a href=""></a>
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title"></h2>
            </div>
            <div class="card-body">
                <p>
                    <a href=""></a>
                  
                    <a href="http://framework.zend.com/archives/"></a>
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"></a></p>
            </div>
        </div>
    </div>
</div>
